// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRnPBrdWgrRjGY1ek91WWEmEFcnQ7acM',
    appId: '1:1083417236907:web:b57a1ef5b1f75f329d2eee',
    messagingSenderId: '1083417236907',
    projectId: 'to-do-list-63d45',
    authDomain: 'to-do-list-63d45.firebaseapp.com',
    storageBucket: 'to-do-list-63d45.firebasestorage.app',
    measurementId: 'G-K5FQY2J0Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnIlulrN3cOoKLciN3ggcZ-AZOeGEhG7g',
    appId: '1:1083417236907:android:1805b5af534896669d2eee',
    messagingSenderId: '1083417236907',
    projectId: 'to-do-list-63d45',
    storageBucket: 'to-do-list-63d45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJNHR8QYmLDMlb6luVUOZ5Ua2U1XOwXQE',
    appId: '1:1083417236907:ios:a835fa2be73d4dd69d2eee',
    messagingSenderId: '1083417236907',
    projectId: 'to-do-list-63d45',
    storageBucket: 'to-do-list-63d45.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJNHR8QYmLDMlb6luVUOZ5Ua2U1XOwXQE',
    appId: '1:1083417236907:ios:a835fa2be73d4dd69d2eee',
    messagingSenderId: '1083417236907',
    projectId: 'to-do-list-63d45',
    storageBucket: 'to-do-list-63d45.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRRnPBrdWgrRjGY1ek91WWEmEFcnQ7acM',
    appId: '1:1083417236907:web:c49d3c97e96a895a9d2eee',
    messagingSenderId: '1083417236907',
    projectId: 'to-do-list-63d45',
    authDomain: 'to-do-list-63d45.firebaseapp.com',
    storageBucket: 'to-do-list-63d45.firebasestorage.app',
    measurementId: 'G-9RVT8X9ZLK',
  );
}
